InfragisticsProductApp/ProductApp.Asp/Models/AccountViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProductApp.Asp.Models
{
    public class AccountViewModels
    {

        public class LoginViewModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe  { get; set; }
        }

        public class RegisterViewModel
        {

            [Required]
            [Display(Name = "Fist Name")]
            public string FirstName { get; set; }

            [Required]
            [Display(Name = "Last Name")]
            public string LastName { get; set; }

            [Required]
            [EmailAddress]
            [Display(Name ="Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {} must be at least {2} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name ="Password")]
            public string Password { get; set; }

            [Required]
            
            [DataType(DataType.Password)]
            [Display(Name = "Confirm Password")]
            [Compare("Password", ErrorMessage = "The password and the confirmation password do not match.")]
            public string ConfirmPassword { get; set; }

        }
    }
}

InfragisticsProductApp/ProductApp.Asp/Models/CheckingAccount.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProductApp.Asp.Models
{
    public class CheckingAccount
    {
        public int Id { get; set; }

        [Required]
        [StringLength(14, ErrorMessage = "The account number length must be 13 or 14 numerics", MinimumLength = 13)]
        [Display(Name = "Account #")]
        public string AccountNumber { get; set; }

        [Required]
        [Display(Name = "Fist Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        public string Name { get {
                return string.Format("{0} {1}", this.FirstName, LastName);
            } }

        [Required]
        [RegularExpression(@"\d+", ErrorMessage = "The balance must be a number")]
        [Range(100, Double.MaxValue, ErrorMessage = "The balance must be $100 at lest")]
        [DataType(DataType.Currency)]
        public decimal Balance { get { return Balance/1; } set { Balance = value; } }
    }
}

InfragisticsProductApp/ProductApp.Asp/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static ProductApp.Asp.Models.AccountViewModels;

namespace ProductApp.Asp.Controllers
{
    public class AccountController : Controller
    {
        // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        // GET: Account/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Account/Create
        public ActionResult Register()
        {
            return View();
        }

        // POST: Account/Create
        [HttpPost]
        public ActionResult Register(RegisterViewModel registerViewModel)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Account/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Account/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Account/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Account/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

InfragisticsProductApp/ProductApp.Asp/Controllers/CheckingAccountController.cs
using ProductApp.Asp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductApp.Asp.Controllers
{
    public class CheckingAccountController : Controller
    {
        // GET: CheckingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: CheckingAccount/Details/5
        public ActionResult Details(int id = 1)
        {
            var checkingAccount = new CheckingAccount { AccountNumber = "02020231412", FirstName = "Quynh", LastName = "Duc", Balance = 500_023_400_100, Id=1};

            return View(checkingAccount);
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

InfragisticsProductApp/ProductApp.Asp/Controllers/HomeController.cs
using ProductApp.Asp.Custom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductApp.Asp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            
            return View();
        }


        [ActionName("what-us")]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View("About");
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Having a trouble? Send us a message!";

            return View();
        }

        [MyFilterAttribute]
        [HttpPost]
        public ActionResult Contact(String txaMessage)
        {
            ViewBag.Message = "Thanks! We recieved your message: " + txaMessage;

            return View();
        }
    }
}

InfragisticsProductApp/ProductApp.Asp/Views/CheckingAccount/Create.cshtml
@model ProductApp.Asp.Models.CheckingAccount

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CheckingAccount</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AccountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InfragisticsProductApp/ProductApp.Asp/Views/CheckingAccount/Details.cshtml
@model ProductApp.Asp.Models.CheckingAccount

@{
    ViewBag.Title = "Details";
}


<div class="row col-md-12">
    <h4 class="margin-top-20">Checking Account's <span style="color:orangered"> @Html.DisplayFor(model => model.Name) </span></h4>
    <div class="col-md-12">
        <hr />
        <div class="col-md-6 offset-md-3">

            <dl class="row">
                <dt class="col-sm text-right">
                    @Html.DisplayNameFor(model => model.AccountNumber)
                </dt>

                <dd class="col-sm">
                    @Html.DisplayFor(model => model.AccountNumber)
                </dd>
            </dl>
            <dl class="row">
                <dt class="col-sm text-right">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd class="col-sm">
                    @Html.DisplayFor(model => model.Name)
                </dd>
            </dl>
            <dl class="row">
                <dt class="col-sm text-right">
                    @Html.DisplayNameFor(model => model.Balance)
                </dt>
                <dd class="col-sm">
                    @Html.DisplayFor(model => model.Balance)
                </dd>
            </dl>
        </div>
    </div>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

InfragisticsProductApp/ProductApp.Asp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

InfragisticsProductApp/ProductApp.Asp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<form method="post">
    <textarea name="txaMessage" ></textarea>
    <input type="submit" name="btnSubmit" value="Send"/>

</form>

InfragisticsProductApp/ProductApp.Asp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Global Bank";
}

@*
    <div class="jumbotron">
        <h1>Global Bank</h1>
        <p class="lead">Global Bank is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://Global Bank" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>
*@

<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-block btn-lg btn-primary">Withdrawal</a>
        <a href="#" class="btn btn-block btn-lg btn-primary">Quick Cash $100</a>
        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-block btn-lg btn-primary">Balance Inquiry</a>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-block btn-lg btn-primary">Print Statement</a>
        <a href="#" class="btn btn-block btn-lg btn-primary">Transfer Funds</a>
        <a href="#" class="btn btn-block btn-lg btn-primary">Deposit</a>
    </div>  
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Register</h2>
        <p>
            Global Bank MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns.
        </p>
        <p><a href="/Account/Register" id="registerLink" class="btn btn-dark">Register</a></p>
    </div>
    <div class="col-md-4">
        <h2>Login</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a href="/Account/Login" id="registerLink" class="btn btn-secondary">Login</a></p>
    </div>

</div>

You are using @Request.Browser.Browser, and that's good

@{
    var amounts = new List<Decimal> { 100, 123.12m, -319, -1232.22m };
}

<ul>
    @foreach (decimal amount in amounts)
    {
        <li>@formatAmount(amount)<text> vnd</text></li>
    }
</ul>

@helper formatAmount(Decimal amount)
{
    var color = "green";

    if (amount < 0)
    {
        color = "red";
    }

    <span style="color:@color">(@String.Format("{0:c}", amount))</span>
}

@section scripts{
    <script>
        var testScriptHTML = true;
    </script>
}

@section customSection {
    <div>
        <span>This is a custom section which was not required to be existed strictly</span>
    </div>
}

InfragisticsProductApp/ProductApp.Asp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{
    ViewBag.Title = "Global Bank";
    var Title = @ViewBag.Title;
   // @Html.Hidden("Title", Title);
}
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Global Bank</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container">
            @*<div class="navbar-header">*@

            <button class="navbar-toggler navbar-toggler-icon" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
            @Html.ActionLink("Global Bank", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            @*</div>*@
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">

                    @*<li class="nav-item"><a href="/Home" class="nav-link">Home</a></li>
                        <li class="nav-item"><a href="/Home/About" class="nav-link">About</a></li>
                        <li class="nav-item"><a href="/Home/Contact" class="nav-link">Contacts</a></li>*@

                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("About", "what-us", "Home", new { area = "what-us" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Contact", "contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>

                <ul class="nav navbar-nav navbar-right mr-auto">
                    <li class="nav-item"><a href="/Account/Register" id="registerLink" class="nav-link">Register</a></li>
                    <li class="nav-item"><a href="/Account/Login" id="loginLink" class="nav-link">Login</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="col-md-12">
                <img src="~/Content/Images/Final-Fantasy-XV.jpg" class="img-fluid w-100" />
            </div>
        </div>
        <div class="mx-auto">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            <p>&copy; @DateTime.Now - My ASP.NET Application</p>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
  
    <use xlink:href="https://raw.githubusercontent.com/frexy/glyph-iconset/master/sprite/sprite.svg"></use>

    @RenderSection("scripts", required: false)
    @RenderSection("customSection", required: false)
</body>
</html>