aspVidly/aspVidly/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace aspVidly.Models
{
    public class Customer

    {
        public int Id { get; set; }

        public String Name { get; set; }

    }
}

aspVidly/aspVidly/Models/Movie.cs
namespace aspVidly.Models
{
    public class Movie
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

aspVidly/aspVidly/ViewModels/RandomMovieViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using aspVidly.Models;

namespace aspVidly.ViewModels
{
    public class RandomMovieViewModel
    {
        public Movie Movie { get; set; }

        public List<Customer> Customers { get; set; }

    }
}

aspVidly/aspVidly/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace aspVidly.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

aspVidly/aspVidly/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using aspVidly.Models;
using aspVidly.Utils;
using aspVidly.ViewModels;

namespace aspVidly.Controllers
{
    public class MoviesController : Controller
    {

        public MoviesController()
        {
            Debug.Listeners.Add(new TextWriterTraceListener("D:\\temp\\test.txt"));
            Debug.AutoFlush = true;
            Debug.WriteLine("test");

            

        }

        // GET: Movies/Random
        public ActionResult Random()
        {
            var movie = new Movie() {Name = "Shrek!"};
            //return View(movie);
            //return Content("Hello world");
            //return HttpNotFound("PAGE NOT FOUND");
            //return new EmptyResult();
            //return RedirectToAction("Index", "Home", new { page=1, name="love" });

            ViewData["Movie"] = movie;
            ViewBag.Movie = movie;

            //var viewResult = new ViewResult {ViewData = {Model = movie}};
            return View(movie) as ViewResult;           
        }

        public ActionResult Transaction()
        {
           
            var movie = new Movie(){Name = "Alice in the Wonderland"};

            var customers = new List<Customer>()
            {
                new Customer {Name = "John"},
                new Customer() {Name = "Alice"},
                new Customer {Name = "Cusomer Random"},

            };

            var randomMovieVM = new RandomMovieViewModel()
            {
                Movie = movie,
                Customers = customers
                
            };

            return View(randomMovieVM) as ViewResult;
        }
            



        public ActionResult Edit(int movieid)
        {       
            NLogger.D("movieid = " + movieid);

            return Content("id=" + movieid);
        }

        public ActionResult Index(int? pageIndex, string sortBy)
        {
            if (!pageIndex.HasValue)
            {
                pageIndex = 1;
            }

            if (String.IsNullOrWhiteSpace(sortBy))
            {
                sortBy = "Name";
            }

            return View(new Movie(){ Name = "Alice in the Wonderland"}) as ViewResult;
        }

        public ActionResult ByReleaseDate(int year, int month)
        {
            return Content(String.Format("year={0}&month={1}", year, month));
        }

        [Route("movies/pop/{year:length(4):max(2018)}/{month:regex(\\d{2}):range(1, 12)}")]
        public ActionResult ByPopYear(int year, int month)
        {
            return View(String.Format("{0}/{1}", year, month));
        }


    }
}

aspVidly/aspVidly/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

aspVidly/aspVidly/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

aspVidly/aspVidly/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

aspVidly/aspVidly/Views/Movies/Index.cshtml
<img src="" alt="" /><div></div>

aspVidly/aspVidly/Views/Movies/Random.cshtml
<!-- Directive -->
@using aspVidly.Models
@model aspVidly.Models.Movie

<!-- Block of declaration -->
@{
    ViewBag.Title = "Random";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Model.Name -> @Model.Name</h3>
<h2>ViewData -> @((ViewData["Movie"] as Movie)?.Name )</h2>
<h1>ViewBag -> @((ViewBag.Movie)?.Name )</h1>

aspVidly/aspVidly/Views/Movies/Transaction.cshtml
@model aspVidly.ViewModels.RandomMovieViewModel

@{
    ViewBag.Title = "Transaction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Transaction</h2>

@{
    var classname = Model.Customers.Count > 5 ? "alert alert-success" : "alert alert-warning";
}

<h2 class="@classname">@Model.Movie.Name</h2>

@if (Model.Customers.Count == 0)
{
    <text> No One has rated this movie before hand.</text>
}
else
{
    <ol>
        @foreach (var cus in Model.Customers)
        {
            <li>@cus.Name</li>
        }

    </ol>
}

aspVidly/aspVidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

aspVidly/aspVidly/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li>@Html.ActionLink("Random", "Random", "Movies")</li>
                <li>@Html.ActionLink("Transaction", "Index", "Movies")</li>
                    
            </ul>
            @*@Html.Partial("_Layout")*@
        </div>
    </div>
</div>